# Red Wine Quality Analysis And Prediction By Data Science And Machine Learning.. 

## Created And Done By:-Anubhav Kumar Gupta

### Libraries Import

In [2]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

### Data Aquisition

In [3]:
df_wine=pd.read_csv('/work/winequality-red.csv')
df_wine

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
3         9.8        6  
4         9.4        5  
...       ...      ...  
1594     10.5        5  
1595     11.2        6  
1596     11.0        6  
1597     10.2        5  
1598     11.0        6  

[1599 rows x 12 columns]

### Shape Of Dataset

In [4]:
df_wine.shape

(1599, 12)

### First 5 Rows

In [5]:
df_wine.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

### Last 5 rows

In [6]:
df_wine.tail()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
1594     10.5        5  
1595     11.2        6  
1596     11.0        6  
1597     10.2        5  
1598     11.0        6

### Data Types Of Features

In [7]:
df_wine.dtypes

fixed acidity           float64
volatile acidity        float64
citric acid             float64
residual sugar          float64
chlorides               float64
free sulfur dioxide     float64
total sulfur dioxide    float64
density                 float64
pH                      float64
sulphates               float64
alcohol                 float64
quality                   int64
dtype: object

### Convert Quality Feature From Integer To Float

In [8]:
df_wine['quality']=df_wine['quality'].astype('float64')

In [9]:
df_wine.dtypes

fixed acidity           float64
volatile acidity        float64
citric acid             float64
residual sugar          float64
chlorides               float64
free sulfur dioxide     float64
total sulfur dioxide    float64
density                 float64
pH                      float64
sulphates               float64
alcohol                 float64
quality                 float64
dtype: object

In [10]:
df_wine[['quality']].head()

quality
0      5.0
1      5.0
2      5.0
3      6.0
4      5.0

### Quality Valuecounts

In [11]:
df_wine[['quality']].value_counts()

quality
5.0        681
6.0        638
7.0        199
4.0         53
8.0         18
3.0         10
dtype: int64

### Memory Usage

In [12]:
df_wine.memory_usage()

Index                     128
fixed acidity           12792
volatile acidity        12792
citric acid             12792
residual sugar          12792
chlorides               12792
free sulfur dioxide     12792
total sulfur dioxide    12792
density                 12792
pH                      12792
sulphates               12792
alcohol                 12792
quality                 12792
dtype: int64

### Descriptive Statistics

In [13]:
df_wine.describe(include='all')

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    1599.000000       1599.000000  1599.000000     1599.000000   
mean        8.319637          0.527821     0.270976        2.538806   
std         1.741096          0.179060     0.194801        1.409928   
min         4.600000          0.120000     0.000000        0.900000   
25%         7.100000          0.390000     0.090000        1.900000   
50%         7.900000          0.520000     0.260000        2.200000   
75%         9.200000          0.640000     0.420000        2.600000   
max        15.900000          1.580000     1.000000       15.500000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  1599.000000          1599.000000           1599.000000  1599.000000   
mean      0.087467            15.874922             46.467792     0.996747   
std       0.047065            10.460157             32.895324     0.001887   
min       0.012000             1.000000              6.000000     0.990070   
25%       0.070000             7.000000             22.000000     0.995600   
50%       0.079000            14.000000             38.000000     0.996750   
75%       0.090000            21.000000             62.000000     0.997835   
max       0.611000            72.000000            289.000000     1.003690   

                pH    sulphates      alcohol      quality  
count  1599.000000  1599.000000  1599.000000  1599.000000  
mean      3.311113     0.658149    10.422983     5.636023  
std       0.154386     0.169507     1.065668     0.807569  
min       2.740000     0.330000     8.400000     3.000000  
25%       3.210000     0.550000     9.500000     5.000000  
50%       3.310000     0.620000    10.200000     6.000000  
75%       3.400000     0.730000    11.100000     6.000000  
max       4.010000     2.000000    14.900000     8.000000

### Columns Name

In [14]:
df_wine.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

### Taking x as Predictor And Independent Variable And Storing Features [['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar','chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density','pH', 'sulphates', 'alcohol']] In It To Predict Quality

In [15]:
x=df_wine[['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol']]

### Taking y as Target And Dependent Variable And Storing Feature [['Quality']] In It

In [16]:
y=df_wine[['quality']]

### Train-Test Split For M.L.

In [17]:
from sklearn.model_selection import train_test_split

### Spliting Dataset 80% For Training And 20% For Testing 

In [18]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=0,test_size=0.2)

### Shape Of Train And Test Dataset

In [19]:
print(x_train.shape,y_train.shape)
print(x_test.shape,y_test.shape)

(1279, 11) (1279, 1)
(320, 11) (320, 1)


### By K-Nearest Neighbors(KNN)

In [20]:
from sklearn.neighbors import KNeighborsClassifier

### Fitting Of KNN

In [21]:
KNN=KNeighborsClassifier(n_neighbors=4)
KNN.fit(x_train,y_train)

/shared-libs/python3.9/py/lib/python3.9/site-packages/sklearn/neighbors/_classification.py:207: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=4)

### Predicting Quality By KNN

In [22]:
y_pred_KNN=KNN.predict(x_test)

### Predicted Quality By KNN

In [23]:
y_pred_KNN

array([5., 5., 7., 6., 6., 5., 5., 6., 5., 5., 5., 5., 5., 5., 5., 5., 7.,
       6., 5., 5., 6., 6., 6., 5., 6., 5., 5., 6., 5., 6., 6., 6., 5., 5.,
       6., 7., 5., 5., 6., 6., 5., 6., 6., 5., 6., 6., 4., 6., 5., 5., 6.,
       5., 4., 6., 5., 5., 5., 5., 5., 5., 5., 6., 6., 5., 5., 5., 5., 5.,
       7., 7., 5., 5., 6., 5., 6., 6., 5., 5., 5., 6., 5., 5., 4., 6., 5.,
       5., 5., 5., 5., 5., 5., 5., 5., 5., 4., 5., 5., 5., 5., 5., 7., 5.,
       6., 6., 6., 6., 6., 7., 6., 5., 6., 5., 6., 6., 5., 7., 5., 7., 6.,
       6., 5., 7., 5., 5., 7., 5., 5., 5., 5., 5., 5., 5., 5., 5., 6., 5.,
       6., 5., 6., 5., 6., 5., 4., 5., 5., 6., 6., 6., 5., 6., 5., 5., 7.,
       6., 6., 6., 5., 6., 6., 6., 5., 6., 5., 6., 6., 5., 6., 5., 6., 5.,
       5., 3., 6., 7., 7., 5., 5., 7., 6., 5., 5., 6., 6., 6., 6., 5., 6.,
       6., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 6., 6., 6., 6.,
       5., 5., 6., 6., 6., 6., 6., 5., 5., 5., 5., 5., 5., 6., 5., 5., 5.,
       5., 7., 7., 5., 5.

### Accuracy Score Import

In [24]:
from sklearn.metrics import accuracy_score

### Accuracy Score For KNN

In [25]:
y_pred_KNN_accuracy=accuracy_score(y_test,y_pred_KNN)
y_pred_KNN_accuracy

0.521875

### By Decision Tree Classifier(DTC)

In [26]:
from sklearn.tree import DecisionTreeClassifier

### Fitting Of DTC

In [27]:
DTC=DecisionTreeClassifier(criterion='entropy',max_depth=5)
DTC.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=5)

### Predicting Quality By DTC

In [28]:
y_pred_DTC=DTC.predict(x_test)

### Predicted Quality By DTC

In [29]:
y_pred_DTC

array([5., 5., 7., 5., 6., 5., 6., 6., 5., 5., 5., 6., 6., 5., 6., 6., 7.,
       6., 5., 5., 7., 5., 6., 6., 5., 5., 5., 7., 5., 5., 6., 5., 5., 6.,
       6., 6., 5., 5., 6., 6., 5., 6., 7., 7., 6., 5., 5., 6., 6., 6., 5.,
       5., 6., 6., 6., 5., 5., 5., 7., 5., 5., 6., 6., 5., 5., 6., 5., 5.,
       7., 7., 5., 6., 5., 5., 6., 5., 5., 5., 5., 6., 6., 5., 6., 5., 6.,
       6., 6., 5., 5., 5., 5., 5., 5., 5., 6., 5., 7., 5., 5., 6., 7., 6.,
       6., 6., 6., 5., 6., 5., 6., 5., 6., 5., 7., 5., 6., 6., 6., 7., 6.,
       6., 5., 6., 5., 5., 7., 6., 5., 5., 6., 7., 5., 5., 6., 7., 6., 5.,
       6., 5., 6., 5., 6., 5., 5., 5., 5., 5., 7., 6., 6., 5., 6., 6., 5.,
       6., 6., 6., 5., 6., 6., 6., 5., 6., 6., 5., 7., 5., 6., 6., 6., 6.,
       7., 5., 5., 7., 5., 7., 5., 7., 5., 5., 5., 6., 6., 6., 6., 5., 6.,
       6., 5., 6., 6., 6., 5., 5., 5., 5., 5., 5., 5., 5., 5., 6., 5., 5.,
       6., 5., 5., 7., 6., 5., 6., 7., 5., 6., 5., 6., 6., 6., 6., 5., 5.,
       5., 7., 5., 6., 6.

### Accuracy Score For DTC

In [30]:
y_pred_DTC_accuracy=accuracy_score(y_test,y_pred_DTC)
y_pred_DTC_accuracy

0.6

### By Random Forest Classifier(RFC)

In [31]:
from sklearn.ensemble import RandomForestClassifier

### Fitting Of RFC

In [32]:
RFC=RandomForestClassifier(max_depth=11)
RFC.fit(x_train,y_train)

/tmp/ipykernel_407/2525705633.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  RFC.fit(x_train,y_train)


RandomForestClassifier(max_depth=11)

### Predicting Quality By RFC

In [33]:
y_pred_RFC=RFC.predict(x_test)

### Predicted Quality By RFC

In [34]:
y_pred_RFC

array([6., 5., 7., 5., 5., 6., 5., 6., 5., 5., 5., 5., 6., 5., 6., 7., 7.,
       5., 5., 5., 6., 5., 6., 6., 5., 5., 5., 7., 5., 6., 6., 6., 6., 5.,
       7., 7., 5., 6., 6., 6., 5., 6., 6., 7., 6., 5., 5., 6., 5., 6., 5.,
       5., 6., 6., 6., 5., 5., 5., 7., 5., 5., 6., 6., 6., 5., 6., 5., 5.,
       7., 6., 6., 5., 5., 5., 6., 6., 5., 5., 5., 7., 6., 5., 6., 6., 6.,
       6., 6., 5., 5., 5., 5., 6., 6., 5., 7., 6., 6., 5., 5., 5., 7., 6.,
       6., 6., 5., 5., 5., 5., 6., 5., 6., 5., 8., 5., 6., 6., 6., 7., 6.,
       6., 5., 6., 5., 5., 6., 7., 5., 5., 6., 6., 5., 5., 6., 5., 6., 5.,
       6., 5., 6., 5., 6., 5., 5., 6., 5., 6., 8., 6., 6., 5., 6., 5., 5.,
       5., 6., 6., 6., 5., 6., 6., 6., 6., 7., 5., 5., 5., 6., 6., 6., 6.,
       6., 6., 5., 7., 5., 6., 7., 7., 7., 5., 5., 7., 6., 6., 6., 5., 5.,
       6., 5., 5., 6., 5., 5., 6., 5., 5., 5., 5., 5., 5., 5., 6., 6., 6.,
       5., 5., 5., 6., 6., 6., 6., 6., 5., 6., 5., 6., 5., 6., 6., 5., 5.,
       6., 6., 5., 6., 6.

### Accuracy Score For RFC

In [35]:
y_pred_RFC_accuracy=accuracy_score(y_test,y_pred_RFC)
y_pred_RFC_accuracy

0.728125

### By Gaussian Naive Bayes(GNB)

In [36]:
from sklearn.naive_bayes import GaussianNB

### Fitting Of GNB

In [37]:
GNB=GaussianNB()
GNB.fit(x_train,y_train)

/shared-libs/python3.9/py/lib/python3.9/site-packages/sklearn/utils/validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB()

### Predicting Quality By GNB

In [38]:
y_pred_GNB=GNB.predict(x_test)

### Predicted Quality By GNN

In [39]:
y_pred_GNB

array([5., 5., 7., 5., 7., 5., 5., 6., 5., 5., 5., 5., 6., 4., 6., 7., 7.,
       6., 6., 5., 6., 5., 6., 6., 6., 5., 5., 7., 5., 6., 6., 6., 5., 5.,
       6., 7., 5., 6., 8., 6., 5., 6., 7., 7., 6., 5., 5., 6., 6., 7., 6.,
       6., 6., 7., 6., 5., 5., 5., 7., 5., 5., 6., 6., 6., 5., 6., 5., 7.,
       6., 6., 5., 4., 5., 5., 5., 6., 5., 5., 5., 7., 6., 5., 6., 6., 6.,
       5., 6., 5., 5., 5., 5., 5., 6., 5., 7., 5., 7., 6., 5., 6., 7., 6.,
       6., 7., 6., 5., 6., 5., 6., 5., 6., 5., 6., 5., 6., 6., 6., 7., 6.,
       6., 5., 6., 4., 5., 8., 7., 5., 5., 6., 7., 5., 5., 6., 6., 7., 5.,
       7., 4., 7., 6., 6., 5., 5., 6., 5., 6., 6., 7., 6., 6., 6., 6., 5.,
       5., 6., 5., 6., 5., 6., 6., 6., 6., 7., 5., 7., 5., 6., 7., 5., 6.,
       7., 6., 5., 7., 6., 6., 6., 7., 6., 5., 5., 8., 5., 7., 8., 5., 5.,
       6., 5., 6., 6., 6., 5., 5., 5., 5., 5., 5., 5., 5., 5., 6., 5., 5.,
       5., 5., 5., 7., 6., 5., 6., 7., 4., 7., 5., 5., 6., 6., 6., 5., 5.,
       6., 7., 6., 5., 7.

### Accuracy Score For GNB

In [40]:
y_pred_GNB_accuracy=accuracy_score(y_test,y_pred_GNB)
y_pred_GNB_accuracy

0.5375

### Outcome Of Analysis And Prediction

#### Random Forest Classifier is the better Classification model to predict quality of red wine because it's accuracy score is 73%(approx) i.e. the actual and predicted test values are very much similar to each other..

### Thanks And Regards,

#### Anubhav Kumar Gupta

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=66716436-298e-4629-baa1-b189c1b9acf5' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>